---
- name: Drop defined databases
  mysql_db:
    name: "{{ item.name }}"
    state: absent
  when: (mysql_recreate_databases is defined and mysql_recreate_databases) or (item.recreate is defined and item.recreate)
  with_items: mysql_databases

- name: Ensure MySQL databases are present
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: mysql_databases
