---
- name: Ensure MySQL rpm repository is installed
  sudo: yes
  yum:
    name: "http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm"
    state: present

###
# TODO: Add disablerepo and replace these..? But they don't persist.
- name: Check if MySQL 5.6 repo is enabled
  ignore_errors: true
  shell: "yum repolist all | grep mysql56-community | grep enabled"
  register: mysql_56_repo_status
  changed_when: false

- name: Enable MySQL 5.6 repo
  shell: "yum-config-manager --disable mysql57-community && yum-config-manager --enable mysql56-community"
  when: not mysql_56_repo_status.stdout_lines
###

- name: Ensure MySQL Python libraries are installed.
  yum: "name=MySQL-python state=installed enablerepo={{ mysql_enablerepo }}"

- name: Ensure MySQL packages are installed.
  yum: "name={{ item }} state=installed enablerepo={{ mysql_enablerepo }}"
  with_items: mysql_packages
  register: rh_mysql_install_packages
